import { NotionProgram } from '../hooks/useNotionPrograms';

/**
 * Generates a clean Markdown representation of a training program.
 */
export function generateProgramMarkdown(program: NotionProgram): string {
  let md = `# ${program.title}\n\n`;
  md += `**Goal**: ${program.goal}\n`;
  md += `**Duration**: ${program.total_weeks} weeks\n`;
  md += `**Current Status**: Week ${program.current_week}, Day ${program.current_day}\n\n`;
  md += `---\n\n`;

  if (program.schedule) {
    for (const weekNum of Object.keys(program.schedule).map(Number).sort()) {
      md += `## Week ${weekNum}\n`;
      const week = program.schedule[weekNum];
      for (const dayNum of Object.keys(week).map(Number).sort()) {
        const workoutId = week[dayNum];
        md += `- **Day ${dayNum}**: Workout ID \`${workoutId}\`\n`;
      }
      md += `\n`;
    }
  }

  md += `\n*Generated by Galawgaw Engine*`;
  return md;
}

/**
 * Triggers a file download for the generated markdown.
 */
export function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
